### ISSUE TITLE
Quit calls to Google

### ISSUE THREAD

**Issue by EibrielInv** [rDany/rdany-web#3]
The site currently calls to:
https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400

We must get rid of that.

**Comment by AlexDvorak** [comment]
where does it call the googlefonts api?

**Comment by EibrielInv** [comment]
Hi Alex! Apparently from the file named: `assets/css/main.css`

**Comment by AlexDvorak** [comment]
Fixed

**Comment by EibrielInv** [comment]
Great! Thanks!
